"""add job_match audit columns

Revision ID: 15eaf3f484ce
Revises: cb7c1c81f1c6
Create Date: 2026-08-27 06:38:37.356845

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '15eaf3f484ce'
down_revision: str | None = 'cb7c1c81f1c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('hard_stop_reasons', sa.JSON(), nullable=False))
    op.add_column('job_matches', sa.Column('excluded_reasons', sa.JSON(), nullable=False))
    op.add_column('job_matches', sa.Column('semantic_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_matches', 'semantic_available')
    op.drop_column('job_matches', 'excluded_reasons')
    op.drop_column('job_matches', 'hard_stop_reasons')
    # ### end Alembic commands ###
