"""add application approvals and allowlist tables

Revision ID: 48d1ebbc5bd9
Revises: 92b5df3ca242
Create Date: 2026-08-27 16:36:39.638456

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '48d1ebbc5bd9'
down_revision: str | None = '92b5df3ca242'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_allowlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_application_allowlist_entries_job_fingerprint',
        'application_allowlist_entries', ['job_fingerprint'], unique=False,
    )
    op.create_table('application_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('posting_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('answer_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_application_approvals_application_id'),
        'application_approvals', ['application_id'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_application_approvals_application_id'), table_name='application_approvals',
    )
    op.drop_table('application_approvals')
    op.drop_index(
        'ix_application_allowlist_entries_job_fingerprint',
        table_name='application_allowlist_entries',
    )
    op.drop_table('application_allowlist_entries')
    # ### end Alembic commands ###
