"""add career os pipeline tracking columns to applications

Revision ID: 5a568d2409c8
Revises: 48d1ebbc5bd9
Create Date: 2026-09-03 09:30:16.857444

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '5a568d2409c8'
down_revision: str | None = '48d1ebbc5bd9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='SAVED' on the NOT NULL pipeline_stage column: SQLite
    # requires a DEFAULT for a NOT-NULL column added via ALTER TABLE, and
    # it also backfills any pre-existing row to the same "just saved,
    # nothing decided yet" starting stage the model's Python-side default
    # already uses for new rows going forward.
    op.add_column(
        'applications',
        sa.Column(
            'pipeline_stage', sa.String(length=32), nullable=False, server_default='SAVED',
        ),
    )
    op.add_column('applications', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column(
        'applications', sa.Column('recruiter_contact', sa.String(length=255), nullable=True),
    )
    op.add_column(
        'applications', sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        'applications', sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column('applications', sa.Column('outcome', sa.String(length=64), nullable=True))
    op.create_index(
        'ix_applications_pipeline_stage', 'applications', ['pipeline_stage'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_pipeline_stage', table_name='applications')
    op.drop_column('applications', 'outcome')
    op.drop_column('applications', 'follow_up_date')
    op.drop_column('applications', 'interview_date')
    op.drop_column('applications', 'recruiter_contact')
    op.drop_column('applications', 'notes')
    op.drop_column('applications', 'pipeline_stage')
    # ### end Alembic commands ###
