"""phase 8 global job intelligence schema

Revision ID: cf8ed6778bde
Revises: 5a568d2409c8
Create Date: 2026-09-03 10:07:24.176619

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'cf8ed6778bde'
down_revision: str | None = '5a568d2409c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'search_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('sources', sa.JSON(), nullable=False),
        sa.Column('queries', sa.JSON(), nullable=False),
        sa.Column('jobs_found', sa.Integer(), nullable=False),
        sa.Column('duplicates_removed', sa.Integer(), nullable=False),
        sa.Column('expired_removed', sa.Integer(), nullable=False),
        sa.Column('qualified', sa.Integer(), nullable=False),
        sa.Column('errors', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'search_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('target_roles', sa.JSON(), nullable=False),
        sa.Column('target_countries', sa.JSON(), nullable=False),
        sa.Column('target_cities', sa.JSON(), nullable=False),
        sa.Column('remote_preference', sa.String(length=16), nullable=True),
        sa.Column('min_salary', sa.Float(), nullable=True),
        sa.Column('max_experience_gap_years', sa.Float(), nullable=True),
        sa.Column('industries', sa.JSON(), nullable=False),
        sa.Column('companies_priority', sa.JSON(), nullable=False),
        sa.Column('companies_excluded', sa.JSON(), nullable=False),
        sa.Column('min_match_score', sa.Integer(), nullable=False),
        sa.Column('search_frequency_hours', sa.Integer(), nullable=False),
        sa.Column('notification_min_score', sa.Integer(), nullable=False),
        sa.Column('notification_frequency', sa.String(length=16), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_search_preferences_candidate_id'),
        'search_preferences', ['candidate_id'], unique=True,
    )
    op.create_table(
        'watchlist_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.String(length=16), nullable=False),
        sa.Column('value', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_watchlist_entries_candidate_id'), 'watchlist_entries', ['candidate_id'],
        unique=False,
    )
    op.create_index(
        'ix_watchlist_entries_candidate_kind', 'watchlist_entries', ['candidate_id', 'kind'],
        unique=False,
    )
    op.add_column(
        'candidate', sa.Column('last_dashboard_view_at', sa.DateTime(timezone=True), nullable=True),
    )
    # server_default='ACTIVE': SQLite requires a DEFAULT for a NOT-NULL
    # column added via ALTER TABLE, and it backfills every pre-existing
    # job row to the same "presumed still live" state new rows get going
    # forward via the model's Python-side default.
    op.add_column(
        'jobs',
        sa.Column('lifecycle_status', sa.String(length=16), nullable=False, server_default='ACTIVE'),
    )
    op.add_column('notifications', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f('ix_notifications_candidate_id'), 'notifications', ['candidate_id'], unique=False,
    )
    # SQLite has no ALTER TABLE ADD CONSTRAINT — batch mode rebuilds the
    # table under the hood to add the foreign key, which plain
    # `op.create_foreign_key` cannot do on this dialect.
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.create_foreign_key(
            'fk_notifications_candidate_id', 'candidate', ['candidate_id'], ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.drop_constraint('fk_notifications_candidate_id', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_candidate_id'), table_name='notifications')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'candidate_id')
    op.drop_column('jobs', 'lifecycle_status')
    op.drop_column('candidate', 'last_dashboard_view_at')
    op.drop_index('ix_watchlist_entries_candidate_kind', table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_candidate_id'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index(op.f('ix_search_preferences_candidate_id'), table_name='search_preferences')
    op.drop_table('search_preferences')
    op.drop_table('search_runs')
    # ### end Alembic commands ###
