"""add candidate_profile_versions table

Revision ID: e60a4fbe27a2
Revises: 15eaf3f484ce
Create Date: 2026-08-27 07:27:51.082129

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'e60a4fbe27a2'
down_revision: str | None = '15eaf3f484ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profile_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('profile_hash', sa.String(length=64), nullable=False),
    sa.Column('resume_file_hash', sa.String(length=64), nullable=False),
    sa.Column('source_file_hashes', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_profile_versions_candidate_id', 'candidate_profile_versions', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_profile_versions_profile_hash', 'candidate_profile_versions', ['profile_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_profile_versions_profile_hash', table_name='candidate_profile_versions')
    op.drop_index('ix_candidate_profile_versions_candidate_id', table_name='candidate_profile_versions')
    op.drop_table('candidate_profile_versions')
    # ### end Alembic commands ###
